version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./config/mysql/init:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mango
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3308:3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci' ]